# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 88720176a2ec4fbb7391ddd1e421fb5e0008b255fa3b857a34da79e12f2022c5063236e5615ea729633766201672be9c5d5c971f27acf83e3cc1cb1ed7e98636

test:
  secret_key_base: 12a37945b1fe4d9432125a2516606e78b12bbbbba3b3074b2e39f60095bce7a701b4430f8f728d61836cdfa2c3a2b6bdcb3d26d278d70ee644b465364c6218bd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
